version: '3.5'

services:
  apache56-prod:
    container_name: hcis_gdps_prod
    ports:
      - "8008:80"
    volumes:
      - .:/var/www/html
    build: .
    environment:
      - TZ=Asia/Jakarta
      - APP_ENV=production
      - APP_DEBUG=false
    restart: always